services:
  postgres:
    container_name: postgres-db
    image: postgres:16.6
    hostname: localhost
    ports:
      - "5433:5432"
    networks:
      - localhost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: licenseplate
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  licenseplate:
    container_name: licenseplate-server
    image: licenseplate:test2
    hostname: localhost
    depends_on:
      - postgres
    networks:
        - localhost
    ports:
      - "8001:8000"
    volumes:
      - /dev/video0:/dev/video0
    devices:
      - /dev/video0
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    restart: unless-stopped

networks:
  localhost:
    external: false

volumes:
  postgres-data:
