version: '3.8'
services:
  postgres:
    container_name: postgres-db
    image: postgres:16.6
    hostname: localhost
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: licenseplate
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  licenseplate:
    container_name: licenseplate-server
    image: licenseplate:test1
    depends_on:
      - postgres
    ports:
      - "8001:8000"
    restart: unless-stopped

volumes:
  postgres-data:
